Algoritmo "1. Média e situação do aluno (cálculo + condição)"
// Leia 2 notas, calcule a media e mostre:
//œ "Aprovado" se media >= 7
//œ "Recuperacao" se media entre 5 e 6.9
//œ "Reprovado" se media < 5
Var
n1: real
n2: real
soma: real

Inicio
escreva("Digite o primeiro número: ")
leia(n1)
escreva("Digite o segundo número: ")
leia(n2)

soma <- n1 + n2
escreva("A soma entre", n1, " e ", n2, " é: ", soma)

Fimalgoritmo