// Secao de Identificacao
// Funcao: Algoritmo simples para somar dois numeros e exibir o resultado.
// Autor: Andre Costa
// Data: 1/16/2026
algoritmo "soma01"


// Sessao de Declaracoes
var
// Cria as variaveis
n1,n2, result : inteiro
inicio
// Secao de Comandos

//atribuir valores aos numeros
n1 <- 4
n2 <- 3

result <- n1 + n2

escreval("A soma de ", n1, " e ", n2, " eh: ", result)

fimalgoritmo
